networks:
    devicehub:
        driver: bridge

services:
    nginx:
        image: "nginx:bookworm"
        container_name: devicehub-nginx
        volumes:
            - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        depends_on:
            - devicehub-app
            - devicehub-websocket
            - devicehub-storage-temp
            - devicehub-storage-plugin-apk
            - devicehub-storage-plugin-image
            - devicehub-api
            - devicehub-auth
            - devicehub-provider
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-mongo:
        image: mongo:7.0
        hostname: devicehub-mongo
        container_name: devicehub-mongo
        ports:
            - 27017:27017
        entrypoint: ["mongod", "--replSet", "devicehub-rs", "--bind_ip_all"]
        healthcheck:
            test: echo "rs.status()" | mongosh --port 27017 --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        networks:
            devicehub:
    devicehub-mongosetup:
        image: mongo:7.0
        container_name: devicehub-mongosetup
        depends_on:
            devicehub-mongo:
                condition: service_healthy
        volumes:
            - ./scripts/mongo_setup.sh:/scripts/mongo_setup.sh
        restart: "no"
        entrypoint: ["bash", "/scripts/mongo_setup.sh"]
        networks:
            devicehub:
    devicehub-migrate:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-migrate
        env_file:
            - scripts/variables.env
        command: stf migrate
        depends_on:
            devicehub-mongosetup:
                condition: service_completed_successfully
        networks:
            devicehub:
    devicehub-app:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-app
        env_file:
            - scripts/variables.env
        command: stf app --port 3000 --auth-url ${STF_URL}/${AUTH_URL} --websocket-url ${STF_URL}/ --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-auth:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-auth
        env_file:
            - scripts/variables.env
        command: stf auth-mock --port 3000 --app-url ${STF_URL} --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-processor001:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-processor001
        env_file:
            - scripts/variables.env
        command: stf processor --name proc001 --connect-app-dealer tcp://devicehub-triproxy-app:7160 --connect-dev-dealer tcp://devicehub-triproxy-dev:7260
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-reaper:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-reaper
        env_file:
            - scripts/variables.env
        command: stf reaper --name reaper001 --connect-push tcp://devicehub-triproxy-dev:7270 --connect-sub tcp://devicehub-triproxy-app:7150 --heartbeat-timeout 30000
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-storage-plugin-apk:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-storage-plugin-apk
        env_file:
            - scripts/variables.env
        command: stf storage-plugin-apk --port 3000 --storage-url http://devicehub-storage-temp/ --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-storage-plugin-image:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-storage-plugin-image
        env_file:
            - scripts/variables.env
        command: stf storage-plugin-image --port 3000 --storage-url ${STF_URL}/ --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-storage-temp:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-storage-temp
        env_file:
            - scripts/variables.env
        command: stf storage-temp --port 3000 --save-dir /tmp --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-triproxy-app:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-triproxy-app
        env_file:
            - scripts/variables.env
        command: stf triproxy app001 --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
        ports:
            - "7150:7150"
            - "7160:7160"
            - "7170:7170"
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-triproxy-dev:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-triproxy-dev
        env_file:
            - scripts/variables.env
        command: stf triproxy --name dev001 --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
        ports:
            - "7250:7250"
            - "7260:7260"
            - "7270:7270"
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-websocket:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-websocket
        env_file:
            - scripts/variables.env
        command: stf websocket --port 3000 --storage-url ${STF_URL}/ --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-api:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-api
        env_file:
            - scripts/variables.env
        command: stf api --port 3000 --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270 --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-api-groups-engine:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-api-groups-engine
        env_file:
            - scripts/variables.env
        command: stf groups-engine --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-provider:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-provider
        env_file:
            - scripts/variables.env
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        command: stf provider --name devicehub-provider --adb-host host.docker.internal --no-cleanup --connect-sub tcp://devicehub-triproxy-dev:7250 --connect-push tcp://devicehub-triproxy-dev:7270 --storage-url ${STF_URL}/ --public-ip ${STF_URL} --min-port=12010 --max-port=12100 --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${STF_URL}/d/devicehub-provider/<%= publicPort %>/"
        networks:
            devicehub:
volumes:
    devicehub-db-volume:
