version: "3"

services:
  mongo1:
    image: mongo:6.0.10
    hostname: mongo1
    container_name: mongo1
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    networks:
      default:
        ipv4_address: 172.19.0.2
  mongo2:
    image: mongo:6.0.10
    hostname: mongo2
    container_name: mongo2
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    networks:
      default:
        ipv4_address: 172.19.0.3
  mongo3:
    image: mongo:6.0.10
    hostname: mongo3
    container_name: mongo3
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    networks:
      default:
        ipv4_address: 172.19.0.4
  mongosetup:
    image: mongo:6.0.10
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts/mongo_setup.sh:/scripts/mongo_setup.sh
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]
  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    networks:
      default:
        ipv4_address: 172.19.0.6
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
