name: Run Playwright Tests

on:
  pull_request:
    paths:
      - '.github/workflows/e2e_tests.yaml'
      - 'lib/**'
      - 'Dockerfile'
      - 'test/e2e/**'
      - 'docker-compose-e2e-tests.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'ui/**'
jobs:
  run-e2e-tests:
    runs-on: self-hosted

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vkcompublisher
          password: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove dangling images
        run: docker image prune -a -f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Run Playwright Tests
        run: docker compose -f docker-compose-e2e-tests.yaml up --build --remove-orphans --exit-code-from devicehub-e2e-tests --abort-on-container-exit devicehub-e2e-tests

      - name: Stop docker compose
        run: docker compose -f docker-compose-e2e-tests.yaml down

      - name: Show logs for devicehub
        if: always()
        run: docker compose -f docker-compose-e2e-tests.yaml logs devicehub

      - name: Show logs for adb and emulator
        if: always()
        run: docker compose -f docker-compose-e2e-tests.yaml logs emulator

      - name: Show logs for e2e tests
        if: always()
        run: docker compose -f docker-compose-e2e-tests.yaml logs devicehub-e2e-tests

      - name: docker compose down
        if: always()
        run: docker compose -f docker-compose-e2e-tests.yaml down --remove-orphans